### ISSUE TITLE
AltSwiftUI vs SwiftUI feature comparison

### ISSUE THREAD

**Issue by wimbledon** [rakutentech/AltSwiftUI#11]
Create an easy to view table with two columns indicating the features of AltSwiftUI vs Apple's SwiftUI.
It would be good for a developer to see the side-by-side comparison.

**Comment by kevinwl02** [comment]
Soon we will upload a more detailed API documentation in the form of GitHub pages. For now you can reference to the features list in the README.

**Comment by kevinwl02** [comment]
Documentation site is added at: https://rakutentech.github.io/AltSwiftUI/
