### ISSUE TITLE
Rename the protocol in the comment to "AltPreviewProvider"

### ISSUE THREAD

**Issue by nodehi** [rakutentech/AltSwiftUI#28]
In Line 16, the name is mentioned as "RPreviewProvider" by mistake, it should have been "AltPreviewProvider".

https://github.com/rakutentech/AltSwiftUI/blob/5f69d9099c51d860d2c5b49eadc419546a424125/Sources/AltSwiftUI/Source/Previews/AltPreviewProvider.swift#L16

**Comment by nodehi** [comment]
same for Line 35 in same file.

**Comment by kevinwl02** [comment]
will be fixed in https://github.com/rakutentech/AltSwiftUI/pull/29
